# Generated by Django 4.0.4 on 2022-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
